// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqxvocrumawhnqsmlhos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxeHZvY3J1bWF3aG5xc21saG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMDYwMTQsImV4cCI6MjA2NDU4MjAxNH0.w9C2MkuxUVbU1vedSOPlefdZn0vRUKnowKYxan_KX38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);